-- Hotel Revenue Intelligence Platform
-- Table: bookings
-- Source: hotel_bookings.csv (Kaggle Hotel Booking Demand Dataset)
-- Generated by: scripts/load_data.py
--
-- 32 original columns + 3 derived columns = 35 total

DROP TABLE IF EXISTS bookings;

CREATE TABLE bookings (
    -- ── Original columns ──────────────────────────────────────────────────────
    hotel                           TEXT,        -- "City Hotel" | "Resort Hotel"
    is_canceled                     INTEGER,     -- 0 = not canceled, 1 = canceled
    lead_time                       INTEGER,     -- days between booking and arrival
    arrival_date_year               INTEGER,     -- 2015 | 2016 | 2017
    arrival_date_month              TEXT,        -- month name, e.g. "July"
    arrival_date_week_number        INTEGER,
    arrival_date_day_of_month       INTEGER,
    stays_in_weekend_nights         INTEGER,
    stays_in_week_nights            INTEGER,
    adults                          INTEGER,
    children                        INTEGER,     -- nulls filled with 0
    babies                          INTEGER,
    meal                            TEXT,
    country                         TEXT,        -- nulls filled with "Unknown"
    market_segment                  TEXT,
    distribution_channel            TEXT,        -- "Direct" | "Corporate" | "TA/TO" | "GDS" | "Undefined"
    is_repeated_guest               INTEGER,
    previous_cancellations          INTEGER,
    previous_bookings_not_canceled  INTEGER,
    reserved_room_type              TEXT,        -- A–P room type codes
    assigned_room_type              TEXT,
    booking_changes                 INTEGER,
    deposit_type                    TEXT,
    agent                           INTEGER,     -- nulls filled with 0
    company                         INTEGER,     -- nulls filled with 0
    days_in_waiting_list            INTEGER,
    customer_type                   TEXT,        -- "Transient" | "Contract" | "Transient-Party" | "Group"
    adr                             REAL,        -- Average Daily Rate (filtered: 0 ≤ adr ≤ 5000)
    required_car_parking_spaces     INTEGER,
    total_of_special_requests       INTEGER,
    reservation_status              TEXT,
    reservation_status_date         TEXT,

    -- ── Derived columns ───────────────────────────────────────────────────────
    total_nights                    INTEGER,     -- stays_in_weekend_nights + stays_in_week_nights
    total_revenue                   REAL,        -- adr * total_nights if not canceled, else 0
    arrival_date                    TEXT         -- YYYY-MM-DD combined from year/month/day fields
);

-- ── Useful indexes ────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_arrival_date        ON bookings (arrival_date);
CREATE INDEX IF NOT EXISTS idx_hotel               ON bookings (hotel);
CREATE INDEX IF NOT EXISTS idx_is_canceled         ON bookings (is_canceled);
CREATE INDEX IF NOT EXISTS idx_distribution_channel ON bookings (distribution_channel);
CREATE INDEX IF NOT EXISTS idx_reserved_room_type  ON bookings (reserved_room_type);
